// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbwchkhaftpynzbinzbp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpid2Noa2hhZnRweW56YmluemJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxNjY4OTgsImV4cCI6MjA3Mzc0Mjg5OH0.xL8L6lAYLqj1Vey4kdAGRdVnZOfHIMI2KKBoAm2gT1Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});